#!/bin/sh -e
VERSION="$1"

if [ -z "$VERSION" ]
then
    echo "You need to specify a version (ex. '1.0.0')"
    exit 1
fi

git tag -a "v$VERSION" -m "v$VERSION"

echo "Moving v1 tag for GitHub Actions"
git tag -a v1 -m v1 -f
git push && git push --tags -f
